# -*- coding: utf-8 -*-
"""
Simulation/crew.py - Crew Activity and Metabolic Profile Module
Models a 4-astronaut crew schedule, including sleep, exercise, routine, and maintenance,
and computes their corresponding thermal, power, and ECLSS metabolic loads.
"""

import numpy as np

class CrewModel:
    def __init__(self, num_astronauts=4):
        self.num_astronauts = num_astronauts
        # 48-hour schedule in seconds (172800 seconds total)
        # We will define a helper function to get activity at time t (in seconds)
        
    def get_activity(self, t_sec):
        """
        Determines the current crew activity based on a 24-hour cycle.
        Cycle:
          00:00 - 08:00 (0 to 28800s)       : Sleep
          08:00 - 10:00 (28800 to 36000s)   : Routine Operations (Breakfast, briefing)
          10:00 - 12:00 (36000 to 43200s)   : Exercise
          12:00 - 14:00 (43200 to 50400s)   : Maintenance (System checks)
          14:00 - 16:00 (50400 to 57600s)   : Routine Operations (Lunch, documentation)
          16:00 - 20:00 (57600 to 72000s)   : Maintenance (Scientific payload work)
          20:00 - 22:00 (72000 to 79200s)   : Routine Operations (Dinner, leisure)
          22:00 - 24:00 (79200 to 86400s)   : Maintenance (Pre-sleep checks)
        Repeats for day 2.
        """
        t_day = int(t_sec) % 86400
        
        if t_day < 28800:
            return "Sleep"
        elif t_day < 36000:
            return "Routine"
        elif t_day < 43200:
            return "Exercise"
        elif t_day < 50400:
            return "Maintenance"
        elif t_day < 57600:
            return "Routine"
        elif t_day < 72000:
            return "Maintenance"
        elif t_day < 79200:
            return "Routine"
        else:
            return "Maintenance"

    def get_metabolic_loads(self, t_sec):
        """
        Returns metabolic loads depending on the crew activity:
          - heat_load (W): Heat generated by the crew
          - o2_cons (kg/s): Oxygen consumption rate
          - co2_prod (kg/s): Carbon dioxide production rate
          - humidity_load (kg/s): Water vapor generation rate
          - power_demand (W): Direct power usage by crew activities (e.g. exercise equipment)
        """
        activity = self.get_activity(t_sec)
        
        if activity == "Sleep":
            # Per astronaut: 80W heat, 0.6 kg/day O2, 0.7 kg/day CO2, 0.8 kg/day H2O
            heat = 80.0
            o2 = 0.6 / 86400.0
            co2 = 0.7 / 86400.0
            h2o = 0.8 / 86400.0
            power = 0.0
        elif activity == "Routine":
            # Per astronaut: 120W heat, 0.84 kg/day O2, 1.0 kg/day CO2, 1.5 kg/day H2O
            heat = 120.0
            o2 = 0.84 / 86400.0
            co2 = 1.0 / 86400.0
            h2o = 1.5 / 86400.0
            power = 200.0  # e.g., lights, personal systems
        elif activity == "Exercise":
            # Per astronaut: 300W heat, 2.0 kg/day O2, 2.4 kg/day CO2, 3.5 kg/day H2O
            heat = 300.0
            o2 = 2.0 / 86400.0
            co2 = 2.4 / 86400.0
            h2o = 3.5 / 86400.0
            power = 1500.0  # treadmill, resistive device
        elif activity == "Maintenance":
            # Per astronaut: 150W heat, 1.0 kg/day O2, 1.2 kg/day CO2, 1.8 kg/day H2O
            heat = 150.0
            o2 = 1.0 / 86400.0
            co2 = 1.2 / 86400.0
            h2o = 1.8 / 86400.0
            power = 800.0  # tools, laptop stations, equipment active
        else:
            # Fallback
            heat = 120.0
            o2 = 0.84 / 86400.0
            co2 = 1.0 / 86400.0
            h2o = 1.5 / 86400.0
            power = 200.0

        return {
            "activity": activity,
            "heat_load": heat * self.num_astronauts,
            "o2_cons": o2 * self.num_astronauts,
            "co2_prod": co2 * self.num_astronauts,
            "humidity_load": h2o * self.num_astronauts,
            "power_demand": power  # Total cabin activity load
        }
