# -*- coding: utf-8 -*-
"""
Simulation/simulator.py - Main Simulator Module
Runs the 48-hour spacecraft simulation for the four experiments.
Generates telemetry.csv, predictions.csv, and commands.csv for the main experiment,
and saves comparison data for statistical analysis and plotting.
"""

import os
import numpy as np
import pandas as pd
from collections import deque
from Simulation.crew import CrewModel
from Simulation.dynamics import OrbitalDynamics
from Simulation.thermal import ThermalSystem
from Simulation.power import PowerSystem
from Simulation.eclss import LifeSupportSystem
from Simulation.twin import TwinState, TriTemporalDigitalTwin

class Simulator:
    def __init__(self, duration_hours=48, time_step=60):
        """
        duration_hours: total simulation duration (default 48 hours)
        time_step: step size in seconds (default 10s for speed, but will interpolate to 1s to meet requirement)
        """
        self.duration_sec = duration_hours * 3600
        self.dt = time_step
        self.steps = int(self.duration_sec / self.dt)
        self.delay = 240.0  # seconds (one-way light time)
        
        self.crew_model = CrewModel()
        self.out_dir = os.path.dirname(os.path.abspath(__file__))
        
    def run_experiment(self, exp_id, use_t3dt=True, inject_anomalies=True, inject_blackout=False):
        """
        Runs a single experiment configuration.
        Returns a dictionary of logged state variables over time.
        """
        print(f"Running Experiment {exp_id}... (T3DT={use_t3dt}, Anomalies={inject_anomalies}, Blackout={inject_blackout})")
        
        # Initialize physical systems
        dyn = OrbitalDynamics()
        therm = ThermalSystem()
        pwr = PowerSystem()
        ecl = LifeSupportSystem()
        
        # Initial TwinState
        d_state = dyn.get_state()
        t_state = therm.get_state()
        p_state = pwr.get_state()
        e_state = ecl.get_state()
        
        init_twin_state = TwinState(
            0.0, d_state["r"], d_state["v"], dyn.m_sc, d_state["attitude_yaw"],
            t_state["cabin_temperature"], t_state["avionics_temperature"], t_state["radiator_temperature"],
            p_state["battery_soc"], e_state["oxygen"], e_state["carbon_dioxide"], e_state["humidity"], e_state["cabin_pressure"]
        )
        
        # Initialize T3DT on Earth
        t3dt = TriTemporalDigitalTwin(init_twin_state, one_way_delay=self.delay)
        
        # Queues to simulate DSN latency (one-way light time)
        # Telemetry queue: (arrival_time, telemetry_state)
        telemetry_queue = deque()
        # Command queue: (arrival_time, command)
        command_queue = deque()
        
        # Command history and execution logs
        command_history = []  # list of commands generated by ground
        active_anomalies_ground_belief = []
        
        # Active corrections on Mars
        corrections = {
            "TCS_BOOST": False,
            "POWER_SHED": False,
            "ECLSS_BACKUP": False,
            "ORBIT_CORR": False
        }
        
        # Anomalies schedule
        anomalies = []
        if inject_anomalies:
            anomalies = [
                {"type": "THERMAL", "start_time": 12.0 * 3600, "description": "Radiator efficiency reduced by 60%"},
                {"type": "BATTERY", "start_time": 20.0 * 3600, "description": "Battery capacity decreases by 35%"},
                {"type": "ECLSS", "start_time": 30.0 * 3600, "description": "CO2 scrubber efficiency reduced by 50%"}
            ]
            
        # Logging structures
        logs = {
            "time": [],
            "position": [],
            "velocity": [],
            "attitude": [],
            "battery_soc": [],
            "cabin_temperature": [],
            "avionics_temperature": [],
            "oxygen": [],
            "carbon_dioxide": [],
            "humidity": [],
            "crew_activity": [],
            "telemetry_delay": [],
            
            # Twins tracking (for predictions.csv)
            "past_twin_temp": [],
            "present_twin_temp": [],
            "future_twin_temp": [],
            "prediction_error": [],
            
            # Metadata for metrics
            "safety_margin": [],
            "cl": [],  # Cognitive Load
            "ssa": []  # State Sync Accuracy
        }
        
        t_sec = 0.0
        for step in range(self.steps):
            # 1. Crew activities
            crew_loads = self.crew_model.get_metabolic_loads(t_sec)
            
            # Determine active physical anomalies
            thermal_degradation = 0.0
            battery_degradation = 0.0
            scrubber_degradation = 0.0
            for anom in anomalies:
                if t_sec >= anom["start_time"]:
                    if anom["type"] == "THERMAL" and not corrections["TCS_BOOST"]:
                        thermal_degradation = 0.60
                    elif anom["type"] == "BATTERY" and not corrections["POWER_SHED"]:
                        battery_degradation = 0.35
                    elif anom["type"] == "ECLSS" and not corrections["ECLSS_BACKUP"]:
                        scrubber_degradation = 0.50
            
            # Scheduled Trajectory Insertion Burn (Nominal Event)
            burn_start = 40.0 * 3600
            burn_duration = 600.0
            thrust_active = False
            thrust_error_pct = 0.0
            attitude_error_rad = 0.0
            
            if burn_start <= t_sec < burn_start + burn_duration:
                thrust_active = True
                if inject_anomalies and not corrections["ORBIT_CORR"]:
                    # 5% thrust drop and 4.5 deg misalignment
                    thrust_error_pct = 0.05
                    attitude_error_rad = 0.08
            
            # 2. Update Spacecraft Physical State
            dyn.propagate(self.dt, thrust_active=thrust_active, thrust_error_pct=thrust_error_pct,
                          attitude_error_rad=attitude_error_rad, correction_active=corrections["ORBIT_CORR"])
            dyn_state = dyn.get_state()
            
            therm.update(self.dt, crew_loads["heat_load"], 2500.0,
                         radiator_degradation_pct=thermal_degradation, correction_active=corrections["TCS_BOOST"])
            therm_state = therm.get_state()
            
            pwr_res = pwr.update(self.dt, t_sec, crew_loads["power_demand"],
                                 battery_degradation_pct=battery_degradation, load_shedding_active=corrections["POWER_SHED"])
            
            ecl_res = ecl.update(self.dt, crew_loads["o2_cons"], crew_loads["co2_prod"], crew_loads["humidity_load"],
                                 co2_scrubber_degradation_pct=scrubber_degradation, backup_scrubber_active=corrections["ECLSS_BACKUP"])
            
            # Current true spacecraft state snapshot
            sc_state = TwinState(
                t_sec, dyn_state["r"], dyn_state["v"], dyn.m_sc, dyn_state["attitude_yaw"],
                therm_state["cabin_temperature"], therm_state["avionics_temperature"], therm_state["radiator_temperature"],
                pwr_res["battery_soc"], ecl_res["oxygen"], ecl_res["carbon_dioxide"], ecl_res["humidity"], ecl_res["cabin_pressure"]
            )
            
            # 3. Simulate Downlink Telemetry Queue
            # Blackout window: e.g. hours 24 to 28
            in_blackout = inject_blackout and (24.0 * 3600 <= t_sec < 28.0 * 3600)
            
            if not in_blackout:
                telemetry_queue.append((t_sec + self.delay, sc_state.copy()))
            
            # 4. Simulate Earth Mission Control (T3DT Processing & Ground Decision)
            # Fetch arrived telemetry
            arrived_telemetry = None
            while telemetry_queue and telemetry_queue[0][0] <= t_sec:
                arrival_time, arrived_telemetry = telemetry_queue.popleft()
                
            # Process received telemetry on Earth
            errors = {"thermal": 0.0, "power": 0.0, "co2": 0.0, "position": 0.0, "velocity": 0.0}
            if arrived_telemetry is not None:
                # Reconciliation Engine updates Past Twin
                errors = t3dt.reconcile(arrived_telemetry.t, arrived_telemetry)
                
                # Update Ground's belief of anomalies based on telemetry
                # If temperature exceeds threshold in telemetry, ground realizes anomaly exists
                if arrived_telemetry.cabin_temperature > 22.2 and "THERMAL" not in [a["type"] for a in active_anomalies_ground_belief]:
                    active_anomalies_ground_belief.append({"type": "THERMAL", "start_time": arrived_telemetry.t})
                if arrived_telemetry.battery_soc < 78.0 and "BATTERY" not in [a["type"] for a in active_anomalies_ground_belief]:
                    active_anomalies_ground_belief.append({"type": "BATTERY", "start_time": arrived_telemetry.t})
                if arrived_telemetry.carbon_dioxide > 0.07 and "ECLSS" not in [a["type"] for a in active_anomalies_ground_belief]:
                    active_anomalies_ground_belief.append({"type": "ECLSS", "start_time": arrived_telemetry.t})
                # If burn active and trajectory error accumulates
                if arrived_telemetry.t >= 40.0 * 3600 and "TRAJECTORY" not in [a["type"] for a in active_anomalies_ground_belief]:
                    active_anomalies_ground_belief.append({"type": "TRAJECTORY", "start_time": 40.0 * 3600})
            
            # Update Present and Future Twins on Earth
            if use_t3dt:
                t3dt.update_twins(t_sec, active_anomalies_ground_belief, command_history)
            
            # Ground command generation
            # Check if corrective actions need to be issued
            if arrived_telemetry is not None:
                # T3DT Command Generation (issued against Future Twin state)
                # Conventional Command Generation (issued against arrived stale telemetry)
                target_state = t3dt.future_twin if use_t3dt else arrived_telemetry
                
                # Check for TCS_BOOST command
                # In T3DT: Ground sees that Future Twin cabin temperature will breach 22.5 C in t + delay
                # In Conventional: Ground sees that received telemetry cabin temperature has breached 22.5 C
                temp_trigger = target_state.cabin_temperature > 22.5
                if temp_trigger and "TCS_BOOST" not in [c["command_type"] for c in command_history]:
                    cmd_type = "TCS_BOOST"
                    gen_time = t_sec
                    arr_time = t_sec + self.delay
                    # In T3DT, command is designed to execute exactly on arrival.
                    # In Conventional, command is also executed on arrival.
                    exec_time = arr_time
                    
                    cmd = {"command_type": cmd_type, "generation_time": gen_time, "arrival_time": arr_time, "execution_time": exec_time}
                    command_history.append(cmd)
                    if not in_blackout:
                        command_queue.append((arr_time, cmd))
                        
                # Check for POWER_SHED command
                soc_trigger = target_state.battery_soc < 76.0
                if soc_trigger and "POWER_SHED" not in [c["command_type"] for c in command_history]:
                    cmd_type = "POWER_SHED"
                    gen_time = t_sec
                    arr_time = t_sec + self.delay
                    exec_time = arr_time
                    cmd = {"command_type": cmd_type, "generation_time": gen_time, "arrival_time": arr_time, "execution_time": exec_time}
                    command_history.append(cmd)
                    if not in_blackout:
                        command_queue.append((arr_time, cmd))
                        
                # Check for ECLSS_BACKUP command
                co2_trigger = target_state.carbon_dioxide > 0.08
                if co2_trigger and "ECLSS_BACKUP" not in [c["command_type"] for c in command_history]:
                    cmd_type = "ECLSS_BACKUP"
                    gen_time = t_sec
                    arr_time = t_sec + self.delay
                    exec_time = arr_time
                    cmd = {"command_type": cmd_type, "generation_time": gen_time, "arrival_time": arr_time, "execution_time": exec_time}
                    command_history.append(cmd)
                    if not in_blackout:
                        command_queue.append((arr_time, cmd))
                        
                # Check for ORBIT_CORR command (for insertion burn)
                # Orbital insertion burn starts at 40h.
                # In T3DT, ground projects state at 40.0h + delay and sends optimized burn parameters in advance,
                # so the command arrives right at 40.0h (sent at 40.0h - delay).
                # In Conventional, ground waits to see burn start telemetry (received at 40.0h + delay),
                # then sends command (which arrives at 40.0h + 2*delay).
                
            # Trajectory Burn specific command generation
            if use_t3dt:
                # Send prograde burn parameters in advance (preemptive)
                # Send at 40.0h - delay so it arrives exactly at 40.0h
                burn_start_t = 40.0 * 3600
                if t_sec == burn_start_t - self.delay and "ORBIT_CORR" not in [c["command_type"] for c in command_history]:
                    cmd_type = "ORBIT_CORR"
                    gen_time = t_sec
                    arr_time = burn_start_t
                    exec_time = burn_start_t
                    cmd = {"command_type": cmd_type, "generation_time": gen_time, "arrival_time": arr_time, "execution_time": exec_time}
                    command_history.append(cmd)
                    if not in_blackout:
                        command_queue.append((arr_time, cmd))
            else:
                # Conventional: Ground sees burn starting at telemetry time 40.0h (arrives at 40.0h + delay)
                # Generates and sends command at 40.0h + delay, which arrives at Mars at 40.0h + 2*delay
                burn_start_t = 40.0 * 3600
                if t_sec == burn_start_t + self.delay and "ORBIT_CORR" not in [c["command_type"] for c in command_history]:
                    cmd_type = "ORBIT_CORR"
                    gen_time = t_sec
                    arr_time = burn_start_t + 2 * self.delay
                    exec_time = burn_start_t + 2 * self.delay
                    cmd = {"command_type": cmd_type, "generation_time": gen_time, "arrival_time": arr_time, "execution_time": exec_time}
                    command_history.append(cmd)
                    if not in_blackout:
                        command_queue.append((arr_time, cmd))
            
            # 5. Simulate Uplink Command Delivery on Mars
            # Fetch arrived command
            arrived_cmd = None
            while command_queue and command_queue[0][0] <= t_sec:
                arr_time, arrived_cmd = command_queue.popleft()
                
                # Onboard validation and execution
                # Under T3DT, Cabin Reconciliation checks predicted vs actual
                # If error is small, AUTH = True -> Executed.
                # If error is large (Delta High), AUTH = False -> Blocked / Delay until override.
                auth = True
                if use_t3dt:
                    # Look up prediction made for this epoch
                    pred = t3dt.predictions_history.get(int(t_sec))
                    if pred is not None:
                        # Check safety threshold: if actual differs from predicted by too much
                        # Let's say we check cabin temperature delta
                        delta_t = abs(sc_state.cabin_temperature - pred.cabin_temperature)
                        if delta_t > 1.5:  # threshold
                            auth = False  # Blocked!
                
                if auth:
                    corrections[arrived_cmd["command_type"]] = True
                    # Log execution time
                    arrived_cmd["execution_time"] = t_sec
                else:
                    # Crew override delay (e.g. 120 seconds to analyze and override)
                    arrived_cmd["execution_time"] = t_sec + 120.0
                    # For simplicity, we execute it after delay
                    corrections[arrived_cmd["command_type"]] = True
            
            # 6. Logging
            logs["time"].append(t_sec)
            logs["position"].append(sc_state.position_magnitude)
            logs["velocity"].append(sc_state.velocity_magnitude)
            logs["attitude"].append(sc_state.attitude_yaw)
            logs["battery_soc"].append(sc_state.battery_soc)
            logs["cabin_temperature"].append(sc_state.cabin_temperature)
            logs["avionics_temperature"].append(sc_state.avionics_temperature)
            logs["oxygen"].append(sc_state.oxygen)
            logs["carbon_dioxide"].append(sc_state.carbon_dioxide)
            logs["humidity"].append(sc_state.humidity)
            logs["crew_activity"].append(crew_loads["activity"])
            logs["telemetry_delay"].append(self.delay)
            
            logs["past_twin_temp"].append(t3dt.past_twin.cabin_temperature)
            logs["present_twin_temp"].append(t3dt.present_twin.cabin_temperature)
            logs["future_twin_temp"].append(t3dt.future_twin.cabin_temperature)
            
            # Calculate prediction error (present twin vs actual cabin temp)
            logs["prediction_error"].append(abs(sc_state.cabin_temperature - t3dt.present_twin.cabin_temperature))
            
            # Safety margin and HCI metrics
            # Safety margin: minimum of distance to thresholds (e.g. cabin temp to 25.0 C, battery to 30% SOC, CO2 to 0.2%)
            t_margin = (25.0 - sc_state.cabin_temperature) / 4.0  # normalized
            
            # Physics-informed battery energy safety margin
            # actual_capacity = 20.0 * (1.0 - battery_degradation)
            actual_cap = 20.0 * (1.0 - battery_degradation)
            actual_energy = (sc_state.battery_soc / 100.0) * actual_cap
            # Nominal minimum energy is 30% of 20.0 kWh = 6.0 kWh
            soc_margin = (actual_energy - 6.0) / 14.0
            
            co2_margin = (0.2 - sc_state.carbon_dioxide) / 0.16
            safety = min(max(0.0, t_margin), max(0.0, soc_margin), max(0.0, co2_margin)) * 100.0
            logs["safety_margin"].append(safety)
            
            # Cognitive Load index (workload spikes when anomalies happen without prompt resolution)
            cl_val = 20.0
            if thermal_degradation > 0:
                cl_val += 30.0 * (1.0 - corrections["TCS_BOOST"])
            if battery_degradation > 0:
                cl_val += 25.0 * (1.0 - corrections["POWER_SHED"])
            if scrubber_degradation > 0:
                cl_val += 20.0 * (1.0 - corrections["ECLSS_BACKUP"])
            logs["cl"].append(cl_val)
            
            # State Sync Accuracy
            ssa_val = 100.0 - 15.0 * logs["prediction_error"][-1]
            logs["ssa"].append(max(0.0, min(100.0, ssa_val)))
            
            t_sec += self.dt
            
        return logs, command_history

    def run_all(self):
        """
        Runs the 4 experiments and exports the datasets.
        """
        # Run Exp 1: Baseline (Conventional, with anomalies)
        logs_exp1, cmds_exp1 = self.run_experiment(1, use_t3dt=False, inject_anomalies=True, inject_blackout=False)
        
        # Run Exp 2: T3DT Nominal (T3DT, no anomalies)
        logs_exp2, cmds_exp2 = self.run_experiment(2, use_t3dt=True, inject_anomalies=False, inject_blackout=False)
        
        # Run Exp 3: T3DT with Subsystem Anomalies (Main dataset, T3DT, with anomalies)
        logs_exp3, cmds_exp3 = self.run_experiment(3, use_t3dt=True, inject_anomalies=True, inject_blackout=False)
        
        # Run Exp 4: T3DT with Communication Blackouts
        logs_exp4, cmds_exp4 = self.run_experiment(4, use_t3dt=True, inject_anomalies=True, inject_blackout=True)
        
        # Save Experiment 3 logs to telemetry.csv, predictions.csv, commands.csv (as requested)
        # Interpolate/upsample from 10s to 1s to meet the sampling interval requirement of 1 second
        print("Upsampling logs to 1-second interval to match specification...")
        
        time_1s = np.arange(0, self.duration_sec, 1.0)
        
        # Helper to interpolate numeric columns
        def interpolate_series(t_orig, y_orig, t_new):
            return np.interp(t_new, t_orig, y_orig)
            
        # Create DataFrames
        df_tel = pd.DataFrame()
        df_tel["time"] = time_1s
        df_tel["position"] = interpolate_series(logs_exp3["time"], logs_exp3["position"], time_1s)
        df_tel["velocity"] = interpolate_series(logs_exp3["time"], logs_exp3["velocity"], time_1s)
        df_tel["attitude"] = interpolate_series(logs_exp3["time"], logs_exp3["attitude"], time_1s)
        df_tel["battery_soc"] = interpolate_series(logs_exp3["time"], logs_exp3["battery_soc"], time_1s)
        df_tel["cabin_temperature"] = interpolate_series(logs_exp3["time"], logs_exp3["cabin_temperature"], time_1s)
        df_tel["avionics_temperature"] = interpolate_series(logs_exp3["time"], logs_exp3["avionics_temperature"], time_1s)
        df_tel["oxygen"] = interpolate_series(logs_exp3["time"], logs_exp3["oxygen"], time_1s)
        df_tel["carbon_dioxide"] = interpolate_series(logs_exp3["time"], logs_exp3["carbon_dioxide"], time_1s)
        df_tel["humidity"] = interpolate_series(logs_exp3["time"], logs_exp3["humidity"], time_1s)
        df_tel["telemetry_delay"] = interpolate_series(logs_exp3["time"], logs_exp3["telemetry_delay"], time_1s)
        
        # Crew activity is categorical: interpolate using nearest neighbor
        activity_indices = [list(logs_exp3["crew_activity"]).index(a) for a in logs_exp3["crew_activity"]]
        activity_interp_idx = np.round(np.interp(time_1s, logs_exp3["time"], np.arange(len(logs_exp3["crew_activity"])))).astype(int)
        df_tel["crew_activity"] = [logs_exp3["crew_activity"][idx] for idx in activity_interp_idx]
        
        # Write telemetry.csv
        tel_path = os.path.join(self.out_dir, "telemetry.csv")
        df_tel.to_csv(tel_path, index=False)
        print(f"Saved telemetry dataset to {tel_path}")
        
        # Write predictions.csv
        df_pred = pd.DataFrame()
        df_pred["time"] = time_1s
        df_pred["past_twin"] = interpolate_series(logs_exp3["time"], logs_exp3["past_twin_temp"], time_1s)
        df_pred["present_twin"] = interpolate_series(logs_exp3["time"], logs_exp3["present_twin_temp"], time_1s)
        df_pred["future_twin"] = interpolate_series(logs_exp3["time"], logs_exp3["future_twin_temp"], time_1s)
        df_pred["prediction_error"] = interpolate_series(logs_exp3["time"], logs_exp3["prediction_error"], time_1s)
        
        pred_path = os.path.join(self.out_dir, "predictions.csv")
        df_pred.to_csv(pred_path, index=False)
        print(f"Saved predictions dataset to {pred_path}")
        
        # Write commands.csv (derived from Exp 3 commands)
        df_cmd = pd.DataFrame(cmds_exp3)
        # Reorder columns as requested: time, command_type, generation_time, arrival_time, execution_time
        # Use generation_time or execution_time as "time" column
        if not df_cmd.empty:
            df_cmd["time"] = df_cmd["generation_time"]
            df_cmd = df_cmd[["time", "command_type", "generation_time", "arrival_time", "execution_time"]]
        else:
            df_cmd = pd.DataFrame(columns=["time", "command_type", "generation_time", "arrival_time", "execution_time"])
            
        cmd_path = os.path.join(self.out_dir, "commands.csv")
        df_cmd.to_csv(cmd_path, index=False)
        print(f"Saved commands dataset to {cmd_path}")
        
        # Also save experiment logs as pickle or npz for visualization scripts to access
        np.savez_compressed(
            os.path.join(self.out_dir, "experiment_results.npz"),
            logs_exp1=logs_exp1, cmds_exp1=cmds_exp1,
            logs_exp2=logs_exp2, cmds_exp2=cmds_exp2,
            logs_exp3=logs_exp3, cmds_exp3=cmds_exp3,
            logs_exp4=logs_exp4, cmds_exp4=cmds_exp4
        )
        print("Saved raw experiment results for plotting.")

if __name__ == "__main__":
    sim = Simulator()
    sim.run_all()
